# Generated by Django 4.1.6 on 2023-05-07 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_qty', models.PositiveIntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='uploads/')),
                ('product_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('product_discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
