# Generated by Django 4.1.6 on 2023-05-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
