# Generated by Django 4.1.6 on 2023-05-07 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('ORGANIC FRUITS', 'Organic Fruits'), ('ORGANIC VEGETABLES', 'Organic Vegetables'), ('FRESH FRUITS', 'Fresh Fruits'), ('FRESH VEGETABLES', 'Fresh Vegetables')], default='ORGANIC FRUITS', max_length=100)),
                ('product_qty', models.PositiveIntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='uploads/')),
                ('product_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('product_discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
