# Generated by Django 4.1.6 on 2023-05-10 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_products_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_discount',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
