# Generated by Django 4.1.6 on 2023-05-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
