# Generated by Django 4.2.1 on 2023-06-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
